version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: webrisetest
      POSTGRES_PASSWORD: webrisetest
      POSTGRES_DB: webrisetest
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: web-rise-test
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/webrisetest
      SPRING_DATASOURCE_USERNAME: webrisetest
      SPRING_DATASOURCE_PASSWORD: webrisetest
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  pg_data: